// app/radarr/[id]/page.tsx
'use client';

import { useEffect, useState } from 'react';
import { useParams, useRouter } from 'next/navigation';
import { getConfig } from '@/lib/config';
import { AppConfig, RadarrMovie } from '@/types';
import Navigation from '@/components/Navigation';
import TorrentSearchModal from '@/components/TorrentSearchModal';
import DeleteMovieModal from '@/components/DeleteMovieModal';
import Link from 'next/link';

export default function MovieDetailPage() {
  const params = useParams();
  const router = useRouter();
  const id = params?.id as string;
  const [config, setConfig] = useState<AppConfig>({});
  const [movie, setMovie] = useState<RadarrMovie | null>(null);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [showTorrentModal, setShowTorrentModal] = useState(false);
  const [showDeleteModal, setShowDeleteModal] = useState(false);

  useEffect(() => {
    const saved = getConfig();
    setConfig(saved);
    if (saved.radarr?.enabled && id) {
      loadMovie(saved, parseInt(id));
    } else {
      setLoading(false);
      if (!saved.radarr?.enabled) {
        setError('Radarr is not enabled');
      }
    }
  }, [id]);

  const loadMovie = async (cfg: AppConfig, movieId: number) => {
    if (!cfg.radarr?.url || !cfg.radarr?.apiKey) {
      setError('Radarr not configured');
      setLoading(false);
      return;
    }

    try {
      const response = await fetch('/api/proxy', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          url: cfg.radarr.url,
          apiKey: cfg.radarr.apiKey,
          endpoint: `/movie/${movieId}`,
        }),
      });

      if (response.ok) {
        const data = await response.json();
        setMovie(data);
      } else {
        setError('Failed to load movie');
      }
    } catch (err) {
      setError('Connection error');
    } finally {
      setLoading(false);
    }
  };

  const getPosterUrl = (item: RadarrMovie) => {
    const posterImage = item.images?.find(img => img.coverType === 'poster');
    const fanartImage = item.images?.find(img => img.coverType === 'fanart');
    const firstImage = item.images?.[0];
    
    const remoteUrl = (posterImage as any)?.remoteUrl || 
                      (fanartImage as any)?.remoteUrl || 
                      (firstImage as any)?.remoteUrl;
    
    if (remoteUrl && (remoteUrl.startsWith('http://') || remoteUrl.startsWith('https://'))) {
      return remoteUrl;
    }
    
    const originalUrl = posterImage?.url || fanartImage?.url || firstImage?.url;
    
    if (!originalUrl) {
      return null;
    }

    if (originalUrl.startsWith('http://') || originalUrl.startsWith('https://')) {
      return originalUrl;
    }

    const serviceConfig = config.radarr;
    if (!serviceConfig?.url || !serviceConfig?.apiKey) {
      return originalUrl;
    }

    const imagePath = encodeURIComponent(originalUrl);
    const serviceUrl = encodeURIComponent(serviceConfig.url);
    const apiKey = encodeURIComponent(serviceConfig.apiKey);
    
    return `/api/image?path=${imagePath}&service=radarr&url=${serviceUrl}&apiKey=${apiKey}`;
  };

  const getFanartUrl = (item: RadarrMovie) => {
    const fanartImage = item.images?.find(img => img.coverType === 'fanart');
    const posterImage = item.images?.find(img => img.coverType === 'poster');
    const firstImage = item.images?.[0];
    
    const remoteUrl = (fanartImage as any)?.remoteUrl || 
                      (posterImage as any)?.remoteUrl || 
                      (firstImage as any)?.remoteUrl;
    
    if (remoteUrl && (remoteUrl.startsWith('http://') || remoteUrl.startsWith('https://'))) {
      return remoteUrl;
    }
    
    const originalUrl = fanartImage?.url || posterImage?.url || firstImage?.url;
    
    if (!originalUrl) {
      return null;
    }

    if (originalUrl.startsWith('http://') || originalUrl.startsWith('https://')) {
      return originalUrl;
    }

    const serviceConfig = config.radarr;
    if (!serviceConfig?.url || !serviceConfig?.apiKey) {
      return originalUrl;
    }

    const imagePath = encodeURIComponent(originalUrl);
    const serviceUrl = encodeURIComponent(serviceConfig.url);
    const apiKey = encodeURIComponent(serviceConfig.apiKey);
    
    return `/api/image?path=${imagePath}&service=radarr&url=${serviceUrl}&apiKey=${apiKey}`;
  };

  const formatDate = (dateString?: string) => {
    if (!dateString) return 'N/A';
    try {
      return new Date(dateString).toLocaleDateString();
    } catch {
      return dateString;
    }
  };

  const formatFileSize = (bytes?: number) => {
    if (!bytes) return 'N/A';
    const sizes = ['B', 'KB', 'MB', 'GB', 'TB'];
    if (bytes === 0) return '0 B';
    const i = Math.floor(Math.log(bytes) / Math.log(1024));
    return Math.round(bytes / Math.pow(1024, i) * 100) / 100 + ' ' + sizes[i];
  };

  const handleDeleteMovie = async (deleteFiles: boolean) => {
    if (!config.radarr?.url || !config.radarr?.apiKey || !movie?.id) {
      throw new Error('Radarr not configured or movie ID missing');
    }

    const response = await fetch('/api/proxy', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({
        url: config.radarr.url,
        apiKey: config.radarr.apiKey,
        endpoint: `/movie/${movie.id}?deleteFiles=${deleteFiles}`,
        method: 'DELETE',
      }),
    });

    if (!response.ok) {
      const errorData = await response.json().catch(() => ({}));
      throw new Error(errorData.error || errorData.message || 'Failed to delete movie');
    }

    // Redirect to movies list after successful deletion
    router.push('/radarr');
  };

  if (!config.radarr?.enabled) {
    return (
      <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
        <Navigation />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="bg-yellow-50 dark:bg-yellow-900 border border-yellow-200 dark:border-yellow-700 rounded-lg p-4">
            <p className="text-yellow-800 dark:text-yellow-200">
              Radarr is not enabled. Please enable it in Settings.
            </p>
          </div>
        </div>
      </div>
    );
  }

  if (loading) {
    return (
      <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
        <Navigation />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="text-center py-12">
            <p className="text-gray-600 dark:text-gray-400">Loading movie details...</p>
          </div>
        </div>
      </div>
    );
  }

  if (error || !movie) {
    return (
      <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
        <Navigation />
        <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">
          <div className="bg-red-50 dark:bg-red-900 border border-red-200 dark:border-red-700 rounded-lg p-4">
            <p className="text-red-800 dark:text-red-200">{error || 'Movie not found'}</p>
          </div>
          <Link
            href="/radarr"
            className="mt-4 inline-block px-4 py-2 bg-radarr text-white rounded-lg hover:bg-orange-400"
          >
            Back to Movies
          </Link>
        </div>
      </div>
    );
  }

  const posterUrl = getPosterUrl(movie);
  const fanartUrl = getFanartUrl(movie);

  return (
    <div className="min-h-screen bg-gray-100 dark:bg-gray-900">
      <Navigation />
      
      {/* Hero Section with Fanart */}
      <div className="relative h-96 overflow-hidden">
        {fanartUrl ? (
          <>
            <div className="absolute inset-0 bg-gradient-to-b from-transparent via-gray-900/50 to-gray-900"></div>
            <img
              src={fanartUrl}
              alt={movie.title}
              className="w-full h-full object-cover"
            />
          </>
        ) : (
          <div className="absolute inset-0 bg-gradient-to-b from-gray-800 to-gray-900"></div>
        )}
        <div className="absolute inset-0 flex items-end">
          <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 w-full pb-8">
            <div className="flex items-end gap-6">
              {/* Poster on the left */}
              {posterUrl ? (
                <div className="hidden md:block flex-shrink-0">
                  <img
                    src={posterUrl}
                    alt={movie.title}
                    className="w-32 rounded-lg shadow-2xl"
                  />
                </div>
              ) : (
                <div className="hidden md:block w-32 aspect-[2/3] bg-gray-200/20 dark:bg-gray-700/20 rounded-lg flex items-center justify-center backdrop-blur-sm">
                  <svg className="w-12 h-12 text-gray-300" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                    <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                  </svg>
                </div>
              )}
              <Link
                href="/radarr"
                className="mb-4 inline-block px-4 py-2 bg-gray-800/80 text-white rounded-lg hover:bg-gray-700/80 backdrop-blur-sm"
              >
                ← Back to Movies
              </Link>
            </div>
          </div>
        </div>
      </div>

      <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-8">

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
          {/* Left Column - Quick Stats */}
          <div className="lg:col-span-1">
            {/* Quick Stats */}
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-6">
              <h3 className="text-lg font-semibold text-gray-900 dark:text-white mb-4">Quick Info</h3>
              <div className="space-y-3">
                <div>
                  <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Status</span>
                  <p className={`mt-1 px-3 py-1 inline-block rounded-full text-sm ${
                    movie.status === 'released' 
                      ? 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200'
                      : movie.status === 'announced'
                      ? 'bg-yellow-100 text-yellow-800 dark:bg-yellow-900 dark:text-yellow-200'
                      : 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200'
                  }`}>
                    {movie.status}
                  </p>
                </div>
                <div>
                  <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Monitored</span>
                  <p className={`mt-1 px-3 py-1 inline-block rounded-full text-sm ${
                    movie.monitored
                      ? 'bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-200'
                      : 'bg-gray-100 text-gray-800 dark:bg-gray-700 dark:text-gray-200'
                  }`}>
                    {movie.monitored ? 'Yes' : 'No'}
                  </p>
                </div>
                <div>
                  <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Has File</span>
                  <p className={`mt-1 px-3 py-1 inline-block rounded-full text-sm ${
                    movie.hasFile
                      ? 'bg-green-100 text-green-800 dark:bg-green-900 dark:text-green-200'
                      : 'bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-200'
                  }`}>
                    {movie.hasFile ? 'Yes' : 'No'}
                  </p>
                </div>
                {movie.certification && (
                  <div>
                    <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Certification</span>
                    <p className="mt-1 text-sm text-gray-900 dark:text-white">{movie.certification}</p>
                  </div>
                )}
                {movie.runtime && (
                  <div>
                    <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Runtime</span>
                    <p className="mt-1 text-sm text-gray-900 dark:text-white">{movie.runtime} minutes</p>
                  </div>
                )}
              </div>
              <button
                onClick={() => setShowTorrentModal(true)}
                className="mt-4 w-full px-4 py-2 bg-radarr text-white rounded-lg hover:bg-orange-400"
              >
                Search Torrents
              </button>
              <button
                onClick={() => setShowDeleteModal(true)}
                className="mt-3 w-full px-4 py-2 bg-red-600 text-white rounded-lg hover:bg-red-700"
              >
                Delete Movie
              </button>
            </div>
          </div>

          {/* Right Column - Details */}
          <div className="lg:col-span-2">
            <div className="bg-white dark:bg-gray-800 rounded-lg shadow-lg p-8">
              <h1 className="text-4xl font-bold text-gray-900 dark:text-white mb-2">
                {movie.title}
              </h1>
              {movie.year && (
                <p className="text-xl text-gray-600 dark:text-gray-400 mb-6">{movie.year}</p>
              )}

              {/* Ratings */}
              {movie.ratings && (
                <div className="flex flex-wrap gap-4 mb-6">
                  {movie.ratings.tmdb && (
                    <div className="flex items-center space-x-2">
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">TMDB:</span>
                      <span className="text-lg font-semibold text-gray-900 dark:text-white">
                        {movie.ratings.tmdb.value.toFixed(1)}/10
                      </span>
                      <span className="text-xs text-gray-500 dark:text-gray-400">
                        ({movie.ratings.tmdb.votes.toLocaleString()} votes)
                      </span>
                    </div>
                  )}
                  {movie.ratings.imdb && (
                    <div className="flex items-center space-x-2">
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">IMDB:</span>
                      <span className="text-lg font-semibold text-gray-900 dark:text-white">
                        {movie.ratings.imdb.value.toFixed(1)}/10
                      </span>
                      <span className="text-xs text-gray-500 dark:text-gray-400">
                        ({movie.ratings.imdb.votes.toLocaleString()} votes)
                      </span>
                    </div>
                  )}
                  {movie.ratings.rottenTomatoes && (
                    <div className="flex items-center space-x-2">
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Rotten Tomatoes:</span>
                      <span className="text-lg font-semibold text-gray-900 dark:text-white">
                        {movie.ratings.rottenTomatoes.value}%
                      </span>
                    </div>
                  )}
                </div>
              )}

              {/* Overview */}
              {movie.overview && (
                <div className="mb-6">
                  <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Overview</h2>
                  <p className="text-gray-700 dark:text-gray-300 leading-relaxed">{movie.overview}</p>
                </div>
              )}

              {/* Genres */}
              {movie.genres && movie.genres.length > 0 && (
                <div className="mb-6">
                  <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Genres</h2>
                  <div className="flex flex-wrap gap-2">
                    {movie.genres.map((genre, index) => (
                      <span
                        key={index}
                        className="px-3 py-1 bg-gray-200 dark:bg-gray-700 text-gray-800 dark:text-gray-200 rounded-full text-sm"
                      >
                        {genre}
                      </span>
                    ))}
                  </div>
                </div>
              )}

              {/* Release Dates */}
              <div className="mb-6">
                <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">Release Dates</h2>
                <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                  {movie.inCinemas && (
                    <div>
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">In Cinemas</span>
                      <p className="text-gray-900 dark:text-white">{formatDate(movie.inCinemas)}</p>
                    </div>
                  )}
                  {movie.physicalRelease && (
                    <div>
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Physical Release</span>
                      <p className="text-gray-900 dark:text-white">{formatDate(movie.physicalRelease)}</p>
                    </div>
                  )}
                  {movie.digitalRelease && (
                    <div>
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Digital Release</span>
                      <p className="text-gray-900 dark:text-white">{formatDate(movie.digitalRelease)}</p>
                    </div>
                  )}
                </div>
              </div>

              {/* File Information */}
              {movie.movieFile && (
                <div className="mb-6">
                  <h2 className="text-xl font-semibold text-gray-900 dark:text-white mb-3">File Information</h2>
                  <div className="bg-gray-50 dark:bg-gray-700 rounded-lg p-4 space-y-2">
                    <div>
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Path:</span>
                      <p className="text-sm text-gray-900 dark:text-white break-all">{movie.movieFile.path}</p>
                    </div>
                    <div>
                      <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Size:</span>
                      <p className="text-sm text-gray-900 dark:text-white">{formatFileSize(movie.movieFile.size)}</p>
                    </div>
                    {movie.movieFile.quality && (
                      <div>
                        <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Quality:</span>
                        <p className="text-sm text-gray-900 dark:text-white">
                          {movie.movieFile.quality.quality.name} ({movie.movieFile.quality.quality.resolution}p)
                        </p>
                      </div>
                    )}
                    {movie.movieFile.dateAdded && (
                      <div>
                        <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Date Added:</span>
                        <p className="text-sm text-gray-900 dark:text-white">{formatDate(movie.movieFile.dateAdded)}</p>
                      </div>
                    )}
                  </div>
                </div>
              )}

              {/* Additional Info */}
              <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {movie.studio && (
                  <div>
                    <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Studio</span>
                    <p className="text-gray-900 dark:text-white">{movie.studio}</p>
                  </div>
                )}
                {movie.imdbId && (
                  <div>
                    <span className="text-sm font-medium text-gray-500 dark:text-gray-400">IMDB ID</span>
                    <p className="text-gray-900 dark:text-white">
                      <a
                        href={`https://www.imdb.com/title/${movie.imdbId}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-600 dark:text-blue-400 hover:underline"
                      >
                        {movie.imdbId}
                      </a>
                    </p>
                  </div>
                )}
                {movie.tmdbId && (
                  <div>
                    <span className="text-sm font-medium text-gray-500 dark:text-gray-400">TMDB ID</span>
                    <p className="text-gray-900 dark:text-white">
                      <a
                        href={`https://www.themoviedb.org/movie/${movie.tmdbId}`}
                        target="_blank"
                        rel="noopener noreferrer"
                        className="text-blue-600 dark:text-blue-400 hover:underline"
                      >
                        {movie.tmdbId}
                      </a>
                    </p>
                  </div>
                )}
                {movie.added && (
                  <div>
                    <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Added to Library</span>
                    <p className="text-gray-900 dark:text-white">{formatDate(movie.added)}</p>
                  </div>
                )}
                {movie.path && (
                  <div>
                    <span className="text-sm font-medium text-gray-500 dark:text-gray-400">Library Path</span>
                    <p className="text-sm text-gray-900 dark:text-white break-all">{movie.path}</p>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </div>

      <TorrentSearchModal
        isOpen={showTorrentModal}
        onClose={() => setShowTorrentModal(false)}
        movie={movie || null}
      />

      <DeleteMovieModal
        isOpen={showDeleteModal}
        onClose={() => setShowDeleteModal(false)}
        movie={movie}
        onDelete={handleDeleteMovie}
      />
    </div>
  );
}

// frontend/app/pages/media/[id].vue
<template>
  <div>
    <!-- Loading -->
    <div v-if="pending" class="flex justify-center py-16">
      <Icon name="mdi:loading" class="w-8 h-8 animate-spin text-primary-500" />
    </div>

    <!-- Error -->
    <div v-else-if="error" class="card p-8 text-center">
      <Icon name="mdi:alert-circle" class="w-12 h-12 mx-auto mb-3 text-red-500" />
      <p class="font-medium text-red-400">Failed to load media</p>
      <p class="text-sm text-gray-500 mt-1">{{ error.message }}</p>
      <NuxtLink to="/" class="btn btn-secondary btn-sm mt-4">Back to Dashboard</NuxtLink>
    </div>

    <!-- Media Details -->
    <div v-else-if="media">
      <!-- Backdrop -->
      <div
        v-if="media.backdropPath"
        class="relative -mx-4 sm:-mx-6 lg:-mx-8 -mt-6 mb-6 h-64 sm:h-80 lg:h-96"
      >
        <img
          :src="getTMDBImageUrl(media.backdropPath, 'original')"
          :alt="media.title"
          class="w-full h-full object-cover"
        />
        <div class="absolute inset-0 bg-gradient-to-t from-gray-950 via-gray-950/60 to-gray-950/20" />

        <!-- Back button on backdrop -->
        <button
          @click="$router.back()"
          class="absolute top-4 left-4 sm:left-6 lg:left-8 bg-black/50 backdrop-blur-sm p-2 rounded-lg hover:bg-black/70 transition-colors"
        >
          <Icon name="mdi:arrow-left" class="w-5 h-5" />
        </button>
      </div>

      <!-- Back button (no backdrop) -->
      <button
        v-else
        @click="$router.back()"
        class="mb-4 flex items-center gap-2 text-gray-400 hover:text-white transition-colors"
      >
        <Icon name="mdi:arrow-left" class="w-5 h-5" />
        <span class="text-sm">Back</span>
      </button>

      <!-- Content -->
      <div class="flex flex-col md:flex-row gap-6 lg:gap-8" :class="{ '-mt-32 relative z-10': media.backdropPath }">
        <!-- Poster -->
        <div class="w-48 md:w-64 flex-shrink-0 mx-auto md:mx-0">
          <div class="aspect-[2/3] rounded-xl overflow-hidden bg-gray-800 shadow-2xl ring-1 ring-white/10">
            <img
              v-if="media.posterPath"
              :src="getTMDBImageUrl(media.posterPath, 'w500')"
              :alt="media.title"
              class="w-full h-full object-cover"
            />
            <div v-else class="w-full h-full flex items-center justify-center text-gray-600">
              <Icon name="mdi:image-off" class="w-16 h-16" />
            </div>
          </div>
        </div>

        <!-- Info -->
        <div class="flex-1 min-w-0">
          <!-- Title -->
          <h1 class="text-3xl lg:text-4xl font-bold mb-2">{{ media.title }}</h1>

          <!-- Meta row -->
          <div class="flex items-center flex-wrap gap-x-4 gap-y-1 text-sm text-gray-400 mb-4">
            <span v-if="media.year" class="flex items-center gap-1">
              <Icon name="mdi:calendar" class="w-4 h-4" />
              {{ media.year }}
            </span>
            <span class="px-2 py-0.5 rounded bg-gray-800 text-xs font-medium uppercase">
              {{ media.type === 'movie' ? 'Movie' : 'TV Show' }}
            </span>
            <span v-if="media.runtime" class="flex items-center gap-1">
              <Icon name="mdi:clock-outline" class="w-4 h-4" />
              {{ Math.floor(media.runtime / 60) }}h {{ media.runtime % 60 }}m
            </span>
            <span v-if="media.numberOfSeasons" class="flex items-center gap-1">
              <Icon name="mdi:television" class="w-4 h-4" />
              {{ media.numberOfSeasons }} Season{{ media.numberOfSeasons !== 1 ? 's' : '' }}
            </span>
            <span v-if="media.numberOfEpisodes" class="flex items-center gap-1">
              {{ media.numberOfEpisodes }} Episodes
            </span>
            <span v-if="media.voteAverage" class="flex items-center gap-1">
              <Icon name="mdi:star" class="w-4 h-4 text-yellow-400" />
              <span class="font-medium text-white">{{ media.voteAverage.toFixed(1) }}</span>
              <span v-if="media.voteCount" class="text-gray-500">({{ media.voteCount.toLocaleString() }})</span>
            </span>
            <span
              v-if="media.status"
              :class="[
                'px-2 py-0.5 text-xs rounded',
                media.status === 'Released' || media.status === 'Returning Series' ? 'bg-green-600/20 text-green-400' :
                media.status === 'Ended' ? 'bg-gray-600/20 text-gray-400' :
                'bg-yellow-600/20 text-yellow-400'
              ]"
            >
              {{ media.status }}
            </span>
          </div>

          <!-- Genres -->
          <div v-if="genres.length" class="flex flex-wrap gap-2 mb-5">
            <span
              v-for="genre in genres"
              :key="genre"
              class="px-3 py-1 bg-gray-800 rounded-full text-sm text-gray-300"
            >
              {{ genre }}
            </span>
          </div>

          <!-- Overview -->
          <div v-if="media.overview" class="mb-6">
            <p class="text-gray-300 leading-relaxed">{{ media.overview }}</p>
          </div>

          <!-- IMDB Link -->
          <div v-if="media.imdbId" class="mb-6">
            <a
              :href="`https://www.imdb.com/title/${media.imdbId}`"
              target="_blank"
              class="inline-flex items-center gap-2 text-sm text-yellow-500 hover:text-yellow-400 transition-colors"
            >
              <Icon name="mdi:open-in-new" class="w-4 h-4" />
              View on IMDb
            </a>
          </div>

          <!-- Actions -->
          <div class="flex flex-wrap gap-2 mb-8">
            <button @click="showSearchModal = true" class="btn btn-primary">
              <Icon name="mdi:magnify" class="w-5 h-5 mr-2" />
              Search Media
            </button>
            <button @click="refreshMetadata" :disabled="refreshing" class="btn btn-secondary">
              <Icon
                :name="refreshing ? 'mdi:loading' : 'mdi:refresh'"
                :class="{ 'animate-spin': refreshing }"
                class="w-5 h-5 mr-2"
              />
              Refresh
            </button>
            <button
              @click="toggleMonitored"
              :disabled="togglingMonitor"
              :class="media.monitored ? 'btn btn-success' : 'btn btn-secondary'"
            >
              <Icon
                :name="togglingMonitor ? 'mdi:loading' : (media.monitored ? 'mdi:eye-check' : 'mdi:eye-off')"
                :class="{ 'animate-spin': togglingMonitor }"
                class="w-5 h-5 mr-2"
              />
              {{ media.monitored ? 'Monitoring' : 'Not Monitoring' }}
            </button>
            <button
              v-if="media.type === 'tv'"
              @click="showTemplateOverride = true"
              class="btn btn-secondary"
            >
              <Icon name="mdi:text-search" class="w-5 h-5 mr-2" />
              Custom Templates
            </button>
            <button @click="deleteConfirm = true" class="btn btn-danger">
              <Icon name="mdi:delete" class="w-5 h-5 mr-2" />
              Delete
            </button>
          </div>
        </div>
      </div>

      <!-- Library Location -->
      <div v-if="libraryPath" class="mt-8">
        <h2 class="text-xl font-semibold mb-4 flex items-center gap-2">
          <Icon name="mdi:folder" class="w-5 h-5 text-gray-500" />
          Library Location
        </h2>
        <div class="card p-4 flex items-center gap-3">
          <Icon name="mdi:folder-open" class="w-5 h-5 text-primary-400 flex-shrink-0" />
          <code class="text-sm text-gray-300 flex-1 truncate">{{ libraryPath }}</code>
          <button
            @click="showEditPath = true"
            class="btn btn-sm btn-secondary"
          >
            <Icon name="mdi:pencil" class="w-4 h-4 mr-1" />
            Edit
          </button>
        </div>
      </div>

      <!-- Episode Manager for TV Shows -->
      <EpisodeManager 
        v-if="media.type === 'tv'"
        :media-id="mediaId"
        :media-title="media.title"
        :tmdb-id="media.tmdbId"
        :original-title="media.originalTitle"
        :release-year="media.year"
        :imdb-id="media.imdbId"
      />

      <!-- Files Section -->
      <div v-if="media.type === 'movie'" class="mt-8">
        <h2 class="text-xl font-semibold mb-4 flex items-center gap-2">
          <Icon name="mdi:file-multiple" class="w-5 h-5 text-gray-500" />
          Files
          <span class="text-sm font-normal text-gray-500">({{ mediaFiles?.length || 0 }})</span>
        </h2>

        <div v-if="mediaFiles && mediaFiles.length" class="space-y-3">
          <div
            v-for="file in mediaFiles"
            :key="file.id"
            class="card p-4"
          >
            <!-- Filename -->
            <div class="flex items-start gap-3 mb-3">
              <Icon name="mdi:video" class="w-5 h-5 text-primary-400 flex-shrink-0 mt-0.5" />
              <div class="flex-1 min-w-0">
                <h3 class="font-medium text-sm truncate">{{ file.filename }}</h3>
                <p class="text-xs text-gray-500 truncate mt-0.5">{{ file.path }}</p>
              </div>
              <span
                v-if="file.matchConfidence"
                class="text-xs text-gray-500 flex-shrink-0"
              >
                {{ (file.matchConfidence * 100).toFixed(0) }}% match
              </span>
            </div>
            
            <!-- Media Info -->
            <div v-if="file.mediaInfo" class="grid grid-cols-2 md:grid-cols-4 gap-3 mt-3 pl-8">
              <!-- Size -->
              <div class="flex items-center gap-2 text-xs">
                <Icon name="mdi:harddisk" class="w-4 h-4 text-gray-400" />
                <div>
                  <p class="text-gray-500">Size</p>
                  <p class="font-medium">{{ file.mediaInfo.sizeFormatted }}</p>
                </div>
              </div>
              
              <!-- Duration -->
              <div class="flex items-center gap-2 text-xs">
                <Icon name="mdi:clock-outline" class="w-4 h-4 text-gray-400" />
                <div>
                  <p class="text-gray-500">Duration</p>
                  <p class="font-medium">{{ file.mediaInfo.durationFormatted }}</p>
                </div>
              </div>
              
              <!-- Resolution -->
              <div v-if="file.mediaInfo.resolution" class="flex items-center gap-2 text-xs">
                <Icon name="mdi:monitor" class="w-4 h-4 text-gray-400" />
                <div>
                  <p class="text-gray-500">Resolution</p>
                  <p class="font-medium">{{ file.mediaInfo.resolution }}</p>
                </div>
              </div>
              
              <!-- Video Codec -->
              <div v-if="file.mediaInfo.videoCodec" class="flex items-center gap-2 text-xs">
                <Icon name="mdi:video-box" class="w-4 h-4 text-gray-400" />
                <div>
                  <p class="text-gray-500">Video</p>
                  <p class="font-medium uppercase">{{ file.mediaInfo.videoCodec }}</p>
                </div>
              </div>
              
              <!-- Audio Codec -->
              <div v-if="file.mediaInfo.audioCodec" class="flex items-center gap-2 text-xs">
                <Icon name="mdi:speaker" class="w-4 h-4 text-gray-400" />
                <div>
                  <p class="text-gray-500">Audio</p>
                  <p class="font-medium uppercase">{{ file.mediaInfo.audioCodec }}</p>
                </div>
              </div>
              
              <!-- Audio Languages -->
              <div v-if="file.mediaInfo.audioLanguages?.length" class="flex items-center gap-2 text-xs">
                <Icon name="mdi:translate" class="w-4 h-4 text-gray-400" />
                <div>
                  <p class="text-gray-500">Audio</p>
                  <p class="font-medium">{{ file.mediaInfo.audioLanguages.join(', ') }}</p>
                </div>
              </div>
              
              <!-- Subtitles -->
              <div v-if="file.mediaInfo.subtitleLanguages?.length" class="flex items-center gap-2 text-xs">
                <Icon name="mdi:subtitles" class="w-4 h-4 text-gray-400" />
                <div>
                  <p class="text-gray-500">Subtitles</p>
                  <p class="font-medium">{{ file.mediaInfo.subtitleLanguages.join(', ') }}</p>
                </div>
              </div>
              
              <!-- Bitrate -->
              <div v-if="file.mediaInfo.bitrate" class="flex items-center gap-2 text-xs">
                <Icon name="mdi:speedometer" class="w-4 h-4 text-gray-400" />
                <div>
                  <p class="text-gray-500">Bitrate</p>
                  <p class="font-medium">{{ Math.round(file.mediaInfo.bitrate) }} kbps</p>
                </div>
              </div>
            </div>

            <!-- Fallback if no media info -->
            <div v-else class="flex flex-wrap gap-1.5 mt-2 pl-8">
              <span v-if="file.size" class="file-badge bg-gray-700/50 text-gray-300">
                {{ formatBytes(file.size) }}
              </span>
              <span v-if="file.parsedQuality" class="file-badge bg-blue-600/20 text-blue-400">
                {{ file.parsedQuality }}
              </span>
              <span v-if="file.parsedCodec" class="file-badge bg-purple-600/20 text-purple-400">
                {{ file.parsedCodec }}
              </span>
              <span v-if="file.parsedSource" class="file-badge bg-green-600/20 text-green-400">
                {{ file.parsedSource }}
              </span>
              <span v-if="file.parsedEdition" class="file-badge bg-orange-600/20 text-orange-400">
                {{ file.parsedEdition }}
              </span>
            </div>
          </div>
        </div>

        <div v-else class="card p-8 text-center text-gray-500">
          <Icon name="mdi:file-off" class="w-10 h-10 mx-auto mb-2" />
          <p class="text-sm">No files linked to this media</p>
        </div>
      </div>

    </div>

    <!-- Edit Path Modal -->
    <EditPathModal
      v-if="media && libraryPath"
      :show="showEditPath"
      :media-id="mediaId"
      :current-path="libraryPath"
      @close="showEditPath = false"
      @updated="handlePathUpdated"
    />

    <!-- Torrent Search Modal -->
    <TorrentSearchModal
      v-model="showSearchModal"
      :initial-query="searchQuery"
      :media-type="media?.type || 'movie'"
      :media-id="mediaId"
      :media-data="mediaData"
      @download="onDownloadStarted"
    />

    <!-- Template Override Modal (TV Shows only) -->
    <ShowTemplateOverrideModal
      v-if="media && media.type === 'tv'"
      v-model="showTemplateOverride"
      :tmdb-id="media.tmdbId"
      :show-title="media.title"
      @saved="toast.success('Custom templates updated')"
    />

    <!-- Delete Modal -->
    <Teleport to="body">
      <div
        v-if="deleteConfirm"
        class="fixed inset-0 bg-black/70 flex items-center justify-center z-50 p-4"
        @click.self="deleteConfirm = false"
      >
        <div class="card p-6 max-w-md w-full">
          <h3 class="text-xl font-semibold mb-2">Delete Media?</h3>
          <p class="text-gray-400 mb-6 text-sm">
            Are you sure you want to delete <strong>"{{ media?.title }}"</strong>?
            This removes it from your library but won't delete actual files on disk.
          </p>
          <div class="flex gap-3">
            <button @click="deleteConfirm = false" class="btn btn-secondary flex-1">Cancel</button>
            <button @click="deleteMedia" :disabled="deleting" class="btn btn-danger flex-1">
              <Icon
                :name="deleting ? 'mdi:loading' : 'mdi:delete'"
                :class="{ 'animate-spin': deleting }"
                class="w-5 h-5 mr-2"
              />
              Delete
            </button>
          </div>
        </div>
      </div>
    </Teleport>
  </div>
</template>

<script setup lang="ts">
import type { TorrentResult } from '~/types/api';

const route = useRoute();
const router = useRouter();
const api = useApi();
const toast = useToast();
const { getTMDBImageUrl, formatBytes, parseGenres } = useFormatters();

const mediaId = computed(() => parseInt(route.params.id as string));

// Fetch media
const { data: media, pending, error, refresh } = await useAsyncData(
  `media-${mediaId.value}`,
  () => api.media.getById(mediaId.value)
);

// Fetch files with detailed info
const { data: mediaFiles, refresh: refreshFiles } = await useAsyncData(
  `media-files-${mediaId.value}`,
  async () => {
    try {
      const response = await $fetch(`${useRuntimeConfig().public.apiBase}/api/media/${mediaId.value}/files`);
      return response as any[];
    } catch (err) {
      console.error('Failed to fetch media files:', err);
      return [];
    }
  }
);

const genres = computed(() => parseGenres(media.value?.genres));

// Library path editing
const showEditPath = ref(false);
const libraryPath = computed(() => media.value?.libraryPath);

const handlePathUpdated = async (newPath: string) => {
  // Refresh media data
  await refresh();
  await refreshFiles();
  toast.success('Library path updated');
};

// Refresh metadata
const refreshing = ref(false);
const refreshMetadata = async () => {
  refreshing.value = true;
  try {
    await refresh();
    toast.success('Metadata refreshed');
  } finally {
    refreshing.value = false;
  }
};

// Torrent search modal
const showSearchModal = ref(false);
const searchQuery = computed(() => {
  if (!media.value) return '';
  return media.value.year
    ? `${media.value.title} ${media.value.year}`
    : media.value.title;
});

const mediaData = computed(() => {
  if (!media.value) return undefined;
  
  return {
    tmdbId: media.value.tmdbId,
    title: media.value.title,
    originalTitle: media.value.originalTitle,
    releaseYear: media.value.year,
    imdbId: media.value.imdbId,
  };
});

// Template override modal
const showTemplateOverride = ref(false);

const onDownloadStarted = () => {
  toast.success('Download started!');
  router.push('/downloads');
};

// Monitor toggle
const togglingMonitor = ref(false);
const toggleMonitored = async () => {
  if (!media.value) return;
  
  togglingMonitor.value = true;
  try {
    const newMonitored = !media.value.monitored;
    const config = useRuntimeConfig();
    await $fetch(`${config.public.apiBase}/api/media/${mediaId.value}/monitored`, {
      method: 'PATCH',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ monitored: newMonitored }),
    });
    
    // Refresh data
    await refresh();
    
    toast.success(newMonitored 
      ? `Started monitoring ${media.value.title}` 
      : `Stopped monitoring ${media.value.title}`
    );
  } catch (err: any) {
    toast.error(`Failed to toggle monitoring: ${err.message}`);
  } finally {
    togglingMonitor.value = false;
  }
};

// Delete
const deleteConfirm = ref(false);
const deleting = ref(false);

const deleteMedia = async () => {
  deleting.value = true;
  try {
    await api.media.delete(mediaId.value);
    toast.success('Media deleted');
    const type = media.value?.type === 'tv' ? 'tv' : 'movies';
    router.push(`/library/${type}`);
  } catch (err: any) {
    toast.error(`Delete failed: ${err.message}`);
  } finally {
    deleting.value = false;
    deleteConfirm.value = false;
  }
};

useHead({
  title: () => `${media.value?.title || 'Loading...'} - Unifarr`,
});
</script>

<style scoped>
.file-badge {
  @apply px-2 py-0.5 text-xs rounded font-medium;
}
</style>
